services:
  - type: web
    name: goalix-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FB_PAGE_TOKEN
        sync: false
      - key: FB_PAGE_ID
        sync: false
      - key: FOOTBALL_API_KEY
        sync: false
